name: Pages

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Theme Git submodules
        run: git submodule init & git submodule update
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: CNAME
        run: cp ./CNAME ./public/CNAME
      - name: Validate
        run: ls ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch